# ==========================
# Module Patient
# ==========================
patientRepo          = ma.dentalTech.repository.modules.patient.jdbc_implementation.PatientRepositoryJdbcImpl
patientService       = ma.dentalTech.service.modules.patient.baseImplementation.PatientServiceImpl
patientController    = ma.dentalTech.mvc.controllers.modules.patient.batch_implentation.PatientControllerImpl

# ==========================
# Module Caisse / Facturation (AYA)
# ==========================
factureRepo          = ma.dentalTech.repository.modules.caisse.jdbc_implementation.FactureRepositoryJdbcImpl
chargesRepo          = ma.dentalTech.repository.modules.caisse.jdbc_implementation.ChargesRepositoryJdbcImpl
revenusRepo          = ma.dentalTech.repository.modules.caisse.jdbc_implementation.RevenuesRepositoryJdbcImpl
sitFinRepo           = ma.dentalTech.repository.modules.caisse.jdbc_implementation.SituationFinanciereRepositoryJdbcImpl

caisseDashboardService     = ma.dentalTech.service.modules.caisse.baseImplementation.CaisseDashboardServiceImpl
caisseDashboardController  = ma.dentalTech.mvc.controllers.modules.caisse.swing_implementation.CaisseDashboardControllerImpl

# ==========================
# Module Dashboard (AYA)
# ==========================
dashboardService               = ma.dentalTech.service.modules.dashboard.baseImplementation.DashboardServiceImpl

# ==========================
# Module RDV (Aicha)
# ==========================
rdv.repository       = ma.dentalTech.repository.modules.rdv.jdbc_implementation.RdvRepositoryJdbcImpl
rdv.service          = ma.dentalTech.service.modules.rdv.baseImplementation.RdvServiceImpl
rdv.controller       = ma.dentalTech.mvc.controllers.modules.rdv.batch_implementation.RdvControllerImpl

# ==========================
# Module Agenda (Aicha)
# ==========================
agendaMensuelRepo    = ma.dentalTech.repository.modules.agenda.jdbc_implementation.AgendaMensuelRepositoryJdbcImpl
detailJourneeRepo    = ma.dentalTech.repository.modules.agenda.jdbc_implementation.DetailJourneeRepositoryJdbcImpl
agendaService        = ma.dentalTech.service.modules.agenda.baseImplementation.AgendaServiceImpl

# ==========================
# Module Liste d'Attente (Aicha)
# ==========================
listeAttente.repository = ma.dentalTech.repository.modules.listeAttente.jdbc_implementation.ListeAttenteRepositoryJdbcImpl
listeAttente.service    = ma.dentalTech.service.modules.listeAttente.baseImplementation.ListeAttenteServiceImpl

# ==========================
# Module Plage Horaire (Aicha)
# ==========================
plageHoraire.repository = ma.dentalTech.repository.modules.plageHoraire.jdbc_implementation.PlageHoraireRepositoryJdbcImpl
plageHoraire.service    = ma.dentalTech.service.modules.plageHoraire.baseImplementation.PlageHoraireServiceImpl


# ==========================
# Module Consultation
# ==========================
consultation.repository        = ma.dentalTech.repository.modules.consultation.jdbc_implementation.ConsultationRepositoryJdbcImpl
interventionMedecin.repository = ma.dentalTech.repository.modules.consultation.jdbc_implementation.InterventionMedecinJdbcImpl

# ==========================
# Module Ordonnance / Prescription / Medicament (Malak)
# ==========================
ordonnance.repository          = ma.dentalTech.repository.modules.ordonnance.jdbc_implementation.OrdonnanceRepositoryJdbcImpl
ordonnance.service    = ma.dentalTech.service.modules.ordonnance.baseImplementation.OrdonnanceServiceImpl
prescription.repository        = ma.dentalTech.repository.modules.ordonnance.jdbc_implementation.PrescriptionRepositoryJdbcImpl
medicament.repository          = ma.dentalTech.repository.modules.ordonnance.jdbc_implementation.MedicamentRepositoryJdbcImpl

# ==========================
# Module Certificat (Malak)
# ==========================
certificat.repository          = ma.dentalTech.repository.modules.certificat.jdbc_implementation.CertificatRepositoryJdbcImpl


# ==========================
# Module Notification (Malak)
# ==========================
notification.repository        = ma.dentalTech.repository.modules.notification.jdbc_implementation.NotificationRepositoryJdbcImpl
notification.service  = ma.dentalTech.service.modules.notification.baseImplementation.NotificationServiceImpl


