# ==========================
# Module Patient
# ==========================
patientRepo        = ma.dentalTech.repository.modules.patient.impl.PatientRepositoryImpl
patientService     = ma.dentalTech.service.modules.patient.impl.PatientServiceImpl
patientController  = ma.dentalTech.mvc.controllers.modules.patient.batch_implentation.PatientControllerImpl

# ==========================
# Module Caisse / Dashboard Caisse
# ==========================
factureRepo        = ma.dentalTech.repository.modules.caisse.impl.FactureRepositoryImpl
chargesRepo        = ma.dentalTech.repository.modules.caisse.impl.ChargesRepositoryImpl
revenusRepo        = ma.dentalTech.repository.modules.caisse.impl.RevenuesRepositoryImpl
sitFinRepo         = ma.dentalTech.repository.modules.caisse.impl.SituationFinanciereRepositoryImpl

caisseDashboardService    = ma.dentalTech.service.modules.caisse.impl.CaisseDashboardServiceImpl
caisseDashboardController = ma.dentalTech.mvc.controllers.modules.caisse.batch_implentation.CaisseDashboardControllerImpl

# ==========================
# Module Dashboard (notifications + users + dossierMedical)
# ==========================
notificationRepo   = ma.dentalTech.repository.modules.users.impl.NotificationRepositoryImpl
utilisateurRepo    = ma.dentalTech.repository.modules.users.impl.UtilisateurRepositoryImpl


consultationRepo   = ma.dentalTech.repository.modules.dossierMedical.impl.ConsultationRepositoryImpl
acteRepo           = ma.dentalTech.repository.modules.dossierMedical.impl.ActeRepositoryImpl
dossierMedicalRepo = ma.dentalTech.repository.modules.dossierMedical.impl.DossierMedicalRepositoryImpl

dashboardService   = ma.dentalTech.service.modules.dashboard.impl.DashboardServiceImpl
dashboardController= ma.dentalTech.mvc.controllers.modules.dashboard.impl.DashboardControllerImpl

# ==========================
# Module RDV  (chez vous il est dans agenda)
# ==========================
rdv.repository     = ma.dentalTech.repository.modules.agenda.impl.RdvRepositoryImpl
rdv.service        = ma.dentalTech.service.modules.agenda.impl.RdvServiceImpl
# rdv.controller   = ma.dentalTech.mvc.controllers.modules.rdv.batch_implentation.RdvControllerImpl

# ==========================
# Module Agenda
# ==========================
agendaMensuelRepo  = ma.dentalTech.repository.modules.agenda.impl.AgendaMensuelRepositoryImpl
detailJourneeRepo  = ma.dentalTech.repository.modules.agenda.impl.DetailJourneeRepositoryImpl
agendaService      = ma.dentalTech.service.modules.agenda.impl.AgendaServiceImpl

# ==========================
# Module Liste d'Attente
# ==========================
listeAttente.repository = ma.dentalTech.repository.modules.agenda.impl.ListeAttenteRepositoryImpl
listeAttente.service    = ma.dentalTech.service.modules.agenda.impl.ListeAttenteServiceImpl

# ==========================
# Module Plage Horaire
# ==========================
plageHoraire.repository = ma.dentalTech.repository.modules.agenda.impl.PlageHoraireRepositoryImpl
plageHoraire.service    = ma.dentalTech.service.modules.agenda.impl.PlageHoraireServiceImpl

rdv.controller=ma.dentalTech.mvc.controllers.modules.agenda.batch_implementation.RdvControllerImpl
listeAttente.controller=ma.dentalTech.mvc.controllers.modules.agenda.batch_implementation.ListeAttenteControllerImpl
agenda.controller=ma.dentalTech.mvc.controllers.modules.agenda.batch_implementation.AgendaControllerImpl
