jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.username=root
jdbc.password=Aichou.2004Nat
jdbc.url=jdbc:mysql://localhost:3307/dentalsoft_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&authenticationPlugins=com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin&defaultAuthenticationPlugin=caching_sha2_password
